{{- range .Articles }}
[[articles]]
link = '''{{ .Link }}'''
title = '''{{ .Title }}'''
summary = '''{{ .Summary }}'''
sourceLink = '''{{ .SourceLink }}'''
sourceTitle = '''{{ .SourceTitle }}'''
date = '''{{ .Date.Format "2006-01-02" }}'''
{{- end }}